spring:
  application:
    name: playground

server:
  port: 8080


springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-playground.html
    doc-expansion: none
  packages-to-scan: com.dirbeq.playground.controller
  api-docs.path: /swagger-playground